import type { DeckDoc } from "@/engine/deck-doc";

/** Serialize a deck's scenes to a TS module that mm-website (or any consumer) can import.
 *  The scenes are emitted as a JSON array literal — valid TS — so the round-trip is lossless. */
export function deckDocToModule(
  doc: DeckDoc,
  opts: { constName?: string; typesImport?: string } = {},
): string {
  const constName = opts.constName ?? "scenes";
  const typesImport = opts.typesImport ?? "@/lib/deck/types";
  const body = JSON.stringify(doc.scenes, null, 2);
  return [
    `// Generated by Morgana from deck "${doc.meta.id}" — edit in Morgana, not here.`,
    `import type { Scene } from "${typesImport}";`,
    ``,
    `export const ${constName}: Scene[] = ${body};`,
    ``,
  ].join("\n");
}
