// Vendors latin woff2 from @fontsource into public/fonts/, copies licenses, and
// generates app/fonts.css (@font-face + default --font-* vars). Run via `npm run sync:fonts`.
import { readFileSync, writeFileSync, mkdirSync, copyFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const manifest = JSON.parse(readFileSync(join(root, "lib/fonts/fonts.json"), "utf8"));
const outDir = join(root, "public/fonts");
mkdirSync(join(outDir, "LICENSES"), { recursive: true });

const faces = [];
for (const f of manifest.families) {
  const pkgDir = join(root, "node_modules/@fontsource", f.pkg);
  const famDir = join(outDir, f.pkg);
  mkdirSync(famDir, { recursive: true });
  const lic = ["LICENSE", "LICENSE.md", "LICENSE.txt"].map((n) => join(pkgDir, n)).find(existsSync);
  if (lic) copyFileSync(lic, join(outDir, "LICENSES", `${f.pkg}.txt`));
  for (const w of f.weights) {
    const src = join(pkgDir, "files", `${f.pkg}-latin-${w}-normal.woff2`);
    if (!existsSync(src)) throw new Error(`missing woff2: ${src} (fix weights in fonts.json)`);
    const fileName = `${f.pkg}-${w}.woff2`;
    copyFileSync(src, join(famDir, fileName));
    faces.push(
      `@font-face { font-family: '${f.family}'; font-style: normal; font-weight: ${w}; font-display: swap; src: url('/fonts/${f.pkg}/${fileName}') format('woff2'); }`,
    );
  }
}

const d = manifest.defaults;
const css =
  `/* GENERATED by scripts/sync-fonts.mjs — do not edit by hand. */\n` +
  `:root {\n` +
  `  --font-display: '${d.display}', system-ui, sans-serif;\n` +
  `  --font-body: '${d.body}', system-ui, sans-serif;\n` +
  `  --font-cursive: '${d.cursive}', cursive;\n` +
  `}\n` +
  faces.join("\n") + "\n";
writeFileSync(join(root, "app/fonts.css"), css);
console.log(`sync-fonts: ${manifest.families.length} families, ${faces.length} faces → app/fonts.css`);
